{
 "title": "S3 Ceph",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "cluster", "query": "dev,stage,prod" }
  ]
 },
 "panels": [
  { "title": "cluster: $cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "cluster" },
  {
   "title": "Bucket Actual Size",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_rgw_bucket_actual_size{cluster=~\"$cluster\",name!~\"rook-ceph-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bucket Utilized Size",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_rgw_bucket_utilized_size{cluster=~\"$cluster\",name!~\"rook-ceph-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Usage Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_rgw_bucket_total_usage_size{cluster=~\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Bucket Number Of Shards",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_rgw_bucket_num_shards{cluster=~\"$cluster\",name!~\"rook-ceph-bucket.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bucket Quota Max Objects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_rgw_bucket_quota_max_objects{cluster=~\"$cluster\",name!~\"rook-ceph-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bucket Number Of Objects",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_rgw_bucket_num_objects{cluster=~\"$cluster\",name!~\"rook-ceph-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "User Usage Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_rgw_user_usage_size{cluster=~\"$cluster\",name!~\"rook-ceph-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bucket Quota Max Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_rgw_bucket_quota_max_size{cluster=~\"$cluster\",name!~\"rook-ceph-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "User Quota Max Size",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_rgw_user_quota_max_size{cluster=~\"$cluster\",name!~\"rook-ceph-.*\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "User Quota Max Objects",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_rgw_user_quota_max_objects{cluster=~\"$cluster\",name!~\"rook-ceph-.*\"}",
     "legendFormat": "{{user}}"
    }
   ]
  }
 ]
}